# Generated by Django 5.0.4 on 2026-05-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priceusd', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='images/')),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('courseId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
