# Generated by Django 5.0.4 on 2024-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_feature_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
