# Generated by Django 5.0.4 on 2024-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_siteusers_delete_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('services', models.CharField(max_length=20)),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
    ]
