# Generated by Django 5.0.4 on 2024-09-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_servicepayments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepayments',
            old_name='services',
            new_name='service',
        ),
    ]
