# Generated by Django 5.0.4 on 2024-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_course_coursepayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='priceusd',
            field=models.FloatField(default=0.0),
        ),
    ]
