# Generated by Django 5.0.4 on 2024-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_course_priceusd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayments',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
